version: '3.3'
services:
  pip_node:
    container_name: "pip_node"
    build:
      context: ./
      dockerfile: Dockerfile
#    working_dir: /var/www/html
#    volumes:
#      - .:/var/www/html
    ports:
      - "3003:3003"
    networks:
      - backend
  pip_redis:
    container_name: "pip_redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend
  pip_webserver:
    container_name: "pip_webserver"
    image: "nginx:latest"
    ports:
      - "3000:3000"
    working_dir: /var/www/html

    volumes:
      - ./:var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
    networks:
      - backend



networks:
  backend:
      driver: 'bridge'
